/*
  Cancel Entry feature (common cancellation for Sales Order/Trip Entry/
  Delivery/Payment) + wiring the ledger to respect it.

  CANCEL/CANCELUSERID/CANCELDATETIME already existed on SALESORDER and
  TRIPENTRY (desktop-app columns); CANCEL/CANCELUSERID/CANCELDATE were
  added by hand to DELIVERY_DETAILS and PAYMENT_DETAILS ahead of this
  script (confirmed via read-only check: both nullable, CANCEL as INT not
  BIT there — unlike SALESORDER/TRIPENTRY's NOT NULL BIT). None of the four
  tables had anywhere to store a cancellation reason, so this adds
  CANCELREMARKS to all four.

  Also updates SP_MOBILE_GET_CUSTOMER_LEDGER so a cancelled Delivery or
  Payment no longer counts toward a customer's ledger — Trip Entry already
  excluded CANCEL = 1 rows (028_ledger_include_trip_entry.sql), so this
  brings Delivery/Payment in line now that they can be cancelled too.
  LedgerService.GetAllCustomersAsync (the "no customer selected" register)
  applies the same exclusion — that query is plain C#-side SQL, not a
  stored procedure, so nothing to change here for it.

  Idempotent — safe to re-run.
*/

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SALESORDER' AND COLUMN_NAME = 'CANCELREMARKS')
    ALTER TABLE dbo.SALESORDER ADD CANCELREMARKS NVARCHAR(500) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TRIPENTRY' AND COLUMN_NAME = 'CANCELREMARKS')
    ALTER TABLE dbo.TRIPENTRY ADD CANCELREMARKS NVARCHAR(500) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'DELIVERY_DETAILS' AND COLUMN_NAME = 'CANCELREMARKS')
    ALTER TABLE dbo.DELIVERY_DETAILS ADD CANCELREMARKS NVARCHAR(500) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PAYMENT_DETAILS' AND COLUMN_NAME = 'CANCELREMARKS')
    ALTER TABLE dbo.PAYMENT_DETAILS ADD CANCELREMARKS NVARCHAR(500) NULL;
GO

IF OBJECT_ID(N'dbo.SP_MOBILE_GET_CUSTOMER_LEDGER', N'P') IS NOT NULL
    DROP PROCEDURE dbo.SP_MOBILE_GET_CUSTOMER_LEDGER;
GO

CREATE PROCEDURE dbo.SP_MOBILE_GET_CUSTOMER_LEDGER
(
    @LOCATIONID INT,
    @CUSTOMERID INT,
    @FROMDATE   DATE = NULL,
    @TODATE     DATE = NULL
)
AS
BEGIN
    SET NOCOUNT ON;

    ;WITH DeliveryTxns AS (
        SELECT
            DD.DELIVERYNO AS TXNNO,
            MIN(DD.DELIVERDATE) AS TXNDATE,
            'Delivery' AS TXNTYPE,
            SUM((SOD.TOTALAMOUNT / NULLIF(SOD.SALESQTY, 0)) * DD.DELIVERYQTY) AS TOTALAMOUNT,
            CAST(0 AS NUMERIC(18,2)) AS RECEIVEDAMOUNT
        FROM dbo.DELIVERY_DETAILS DD
        INNER JOIN dbo.SALESORDER_DETAILS SOD ON SOD.SALESORDERDETID = DD.SALESORDERDETID
        INNER JOIN dbo.SALESORDER SO ON SO.SALESORDERID = DD.SALESORDERID
        WHERE SO.CUSTOMERID = @CUSTOMERID AND SO.LOCATIONID = @LOCATIONID
          AND (DD.CANCEL IS NULL OR DD.CANCEL = 0)
        GROUP BY DD.DELIVERYNO
    ),
    TripTxns AS (
        SELECT
            TE.ENTRYNO AS TXNNO,
            TE.TRIPDATE AS TXNDATE,
            'Trip Entry' AS TXNTYPE,
            TE.NETAMOUNT AS TOTALAMOUNT,
            CAST(0 AS NUMERIC(18,2)) AS RECEIVEDAMOUNT
        FROM dbo.TRIPENTRY TE
        WHERE TE.CUSTOMERID = @CUSTOMERID AND TE.LOCATIONID = @LOCATIONID AND TE.CANCEL = 0
    ),
    PaymentTxns AS (
        SELECT
            PD.PAYMENTNO AS TXNNO,
            PD.PAYMENTDATE AS TXNDATE,
            'Payment' AS TXNTYPE,
            CAST(0 AS NUMERIC(18,2)) AS TOTALAMOUNT,
            PD.AMOUNT AS RECEIVEDAMOUNT
        FROM dbo.PAYMENT_DETAILS PD
        WHERE PD.CUSTOMERID = @CUSTOMERID AND PD.LOCATIONID = @LOCATIONID
          AND (PD.CANCEL IS NULL OR PD.CANCEL = 0)
    ),
    Combined AS (
        SELECT * FROM DeliveryTxns
        UNION ALL
        SELECT * FROM TripTxns
        UNION ALL
        SELECT * FROM PaymentTxns
    ),
    Running AS (
        SELECT
            TXNDATE, TXNTYPE, TXNNO, TOTALAMOUNT, RECEIVEDAMOUNT,
            SUM(TOTALAMOUNT - RECEIVEDAMOUNT) OVER (
                ORDER BY TXNDATE, TXNNO
                ROWS UNBOUNDED PRECEDING
            ) AS OUTSTANDINGAMOUNT
        FROM Combined
    )
    SELECT TXNDATE, TXNTYPE, TXNNO, TOTALAMOUNT, RECEIVEDAMOUNT, OUTSTANDINGAMOUNT
    FROM Running
    WHERE (@FROMDATE IS NULL OR CAST(TXNDATE AS DATE) >= @FROMDATE)
      AND (@TODATE IS NULL OR CAST(TXNDATE AS DATE) <= @TODATE)
    ORDER BY TXNDATE, TXNNO;
END
GO
