/*
  Sales Entry — consolidates existing Delivery/Trip Entry activity (for one
  customer) into a formal dbo.SALES invoice + dbo.SALES_DETAILS lines.

  dbo.SALES/dbo.SALES_DETAILS already exist on db_ams_erp/DB_AMS_ERP_SMS as
  real, actively-used desktop tables (confirmed via read-only check — SALES
  has a live TRANSACTIONS row, NAME='SALES', SHORTNAME='SEM/26-27/',
  LASTNO=774 at the time of writing) — this script only creates them where
  missing (the sandbox), matching their exact prod column shapes so SALESID/
  SALESDETID inserts behave identically everywhere. TRANSACTIONS already has
  a 'SALES' row with a live LASTNO on every database (shared with the
  desktop app's own Sales entries, same convention as every other entry
  type here) — nothing to seed there.

  Also adds ISSALES (INT NOT NULL DEFAULT 0) to DELIVERY_DETAILS and
  TRIPENTRY — already present on db_ams_pos_test (added ahead of this
  script) but missing on both prod databases. Set to 1 once a Delivery/Trip
  Entry has been folded into a Sales entry, so it's excluded from being
  selected again.

  Idempotent — safe to re-run.
*/

IF OBJECT_ID(N'dbo.SALES', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.SALES
    (
        SALESID             INT IDENTITY(1,1) NOT NULL,
        ENTRYNO             VARCHAR(50)   NOT NULL,
        ENTRYDATE           DATETIME      NULL,
        SALESORDERID        INT           NOT NULL CONSTRAINT DF_SALES_SALESORDERID DEFAULT 0,
        LOCATIONID          INT           NOT NULL CONSTRAINT DF_SALES_LOCATIONID DEFAULT 0,
        COUNTERID           INT           NOT NULL CONSTRAINT DF_SALES_COUNTERID DEFAULT 0,
        MOBILENO            VARCHAR(50)   NULL,
        CUSTOMERID          INT           NOT NULL CONSTRAINT DF_SALES_CUSTOMERID DEFAULT 0,
        PAYMENTMODE         VARCHAR(20)   NULL,
        TAXABLEVALUE        NUMERIC(18,2) NOT NULL CONSTRAINT DF_SALES_TAXABLEVALUE DEFAULT 0,
        TOTALTAX            NUMERIC(18,2) NOT NULL CONSTRAINT DF_SALES_TOTALTAX DEFAULT 0,
        ITEMVALUE           NUMERIC(18,2) NOT NULL CONSTRAINT DF_SALES_ITEMVALUE DEFAULT 0,
        DISCOUNTPERCENTAGE  NUMERIC(18,2) NOT NULL CONSTRAINT DF_SALES_DISCOUNTPERCENTAGE DEFAULT 0,
        DISCOUNTAMOUNT      NUMERIC(18,2) NOT NULL CONSTRAINT DF_SALES_DISCOUNTAMOUNT DEFAULT 0,
        ROUNDOFF            NUMERIC(18,2) NOT NULL CONSTRAINT DF_SALES_ROUNDOFF DEFAULT 0,
        NETAMOUNT           NUMERIC(18,2) NOT NULL CONSTRAINT DF_SALES_NETAMOUNT DEFAULT 0,
        SELECTRATE          BIT           NOT NULL CONSTRAINT DF_SALES_SELECTRATE DEFAULT 0,
        CASHAMOUNT          NUMERIC(18,2) NOT NULL CONSTRAINT DF_SALES_CASHAMOUNT DEFAULT 0,
        CARDAMOUNT          NUMERIC(18,2) NOT NULL CONSTRAINT DF_SALES_CARDAMOUNT DEFAULT 0,
        REFNO               VARCHAR(50)   NULL,
        RECEIVEDAMOUNT      NUMERIC(18,2) NOT NULL CONSTRAINT DF_SALES_RECEIVEDAMOUNT DEFAULT 0,
        REFUNDAMOUNT        NUMERIC(18,2) NOT NULL CONSTRAINT DF_SALES_REFUNDAMOUNT DEFAULT 0,
        SETTLEMENT          BIT           NOT NULL CONSTRAINT DF_SALES_SETTLEMENT DEFAULT 0,
        SETTLEMENTID        INT           NOT NULL CONSTRAINT DF_SALES_SETTLEMENTID DEFAULT 0,
        PAYMENT             BIT           NOT NULL CONSTRAINT DF_SALES_PAYMENT DEFAULT 0,
        CANCELUSERID        INT           NOT NULL CONSTRAINT DF_SALES_CANCELUSERID DEFAULT 0,
        CANCELID            INT           NOT NULL CONSTRAINT DF_SALES_CANCELID DEFAULT 0,
        CANCEL              BIT           NOT NULL CONSTRAINT DF_SALES_CANCEL DEFAULT 0,
        CANCELDATETIME      DATETIME      NULL,
        CREATEDLOCATIONID   INT           NOT NULL CONSTRAINT DF_SALES_CREATEDLOCATIONID DEFAULT 0,
        MODIFYEDLOCATIONID  INT           NOT NULL CONSTRAINT DF_SALES_MODIFYEDLOCATIONID DEFAULT 0,
        CREATEDUSERID       INT           NOT NULL CONSTRAINT DF_SALES_CREATEDUSERID DEFAULT 0,
        LASTMODIFYEDUSERID  INT           NOT NULL CONSTRAINT DF_SALES_LASTMODIFYEDUSERID DEFAULT 0,
        USERCREATEDDATE     DATETIME      NULL,
        LASTMODIFYEDDATE    DATETIME      NULL,
        CREATEDEMPLOYEEID   INT           NOT NULL CONSTRAINT DF_SALES_CREATEDEMPLOYEEID DEFAULT 0,
        MODIFYEDEMPLOYEEID  INT           NOT NULL CONSTRAINT DF_SALES_MODIFYEDEMPLOYEEID DEFAULT 0,
        SHIPPINGADDRESS     VARCHAR(500)  NULL,
        CUSTOMERNAME        VARCHAR(100)  NULL,
        DCNO                VARCHAR(15)   NULL,
        ORDERDATE           DATE          NULL,
        VEHICLENO           VARCHAR(15)   NULL
    );
END
GO

IF OBJECT_ID(N'dbo.SALES_DETAILS', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.SALES_DETAILS
    (
        SALESID             INT           NOT NULL,
        SALESDETID          INT IDENTITY(1,1) NOT NULL,
        COMPANYID           INT           NOT NULL CONSTRAINT DF_SALES_DETAILS_COMPANYID DEFAULT 0,
        COUNTERID           INT           NOT NULL CONSTRAINT DF_SALES_DETAILS_COUNTERID DEFAULT 0,
        BARCODE             VARCHAR(50)   NULL,
        PRODUCTID           INT           NOT NULL CONSTRAINT DF_SALES_DETAILS_PRODUCTID DEFAULT 0,
        PRODUCTCODE         VARCHAR(50)   NULL,
        HSNCODE             VARCHAR(50)   NULL,
        BRANDID             INT           NOT NULL CONSTRAINT DF_SALES_DETAILS_BRANDID DEFAULT 0,
        TYPEID              INT           NOT NULL CONSTRAINT DF_SALES_DETAILS_TYPEID DEFAULT 0,
        UOMID               INT           NOT NULL CONSTRAINT DF_SALES_DETAILS_UOMID DEFAULT 0,
        WEIGHT              NUMERIC(18,2) NOT NULL CONSTRAINT DF_SALES_DETAILS_WEIGHT DEFAULT 0,
        QTY                 NUMERIC(18,2) NOT NULL CONSTRAINT DF_SALES_DETAILS_QTY DEFAULT 0,
        MRP                 NUMERIC(9,3)  NULL,
        RATE                NUMERIC(9,3)  NULL,
        GROSSAMOUNT         NUMERIC(18,2) NOT NULL CONSTRAINT DF_SALES_DETAILS_GROSSAMOUNT DEFAULT 0,
        DISCOUNTPERCENTAGE  NUMERIC(18,2) NOT NULL CONSTRAINT DF_SALES_DETAILS_DISCOUNTPERCENTAGE DEFAULT 0,
        DISCOUNTAMOUNT      NUMERIC(18,2) NOT NULL CONSTRAINT DF_SALES_DETAILS_DISCOUNTAMOUNT DEFAULT 0,
        OTHERDISCOUNTAMOUNT NUMERIC(18,2) NOT NULL CONSTRAINT DF_SALES_DETAILS_OTHERDISCOUNTAMOUNT DEFAULT 0,
        TAXABLEVALUE        NUMERIC(18,2) NOT NULL CONSTRAINT DF_SALES_DETAILS_TAXABLEVALUE DEFAULT 0,
        CGSTPERCENTAGE      NUMERIC(18,2) NOT NULL CONSTRAINT DF_SALES_DETAILS_CGSTPERCENTAGE DEFAULT 0,
        CGSTAMOUNT          NUMERIC(18,2) NOT NULL CONSTRAINT DF_SALES_DETAILS_CGSTAMOUNT DEFAULT 0,
        SGSTPERCENTAGE      NUMERIC(18,2) NOT NULL CONSTRAINT DF_SALES_DETAILS_SGSTPERCENTAGE DEFAULT 0,
        SGSTAMOUNT          NUMERIC(18,2) NOT NULL CONSTRAINT DF_SALES_DETAILS_SGSTAMOUNT DEFAULT 0,
        IGSTPERCENTAGE      NUMERIC(18,2) NOT NULL CONSTRAINT DF_SALES_DETAILS_IGSTPERCENTAGE DEFAULT 0,
        IGSTAMOUNT          NUMERIC(18,2) NOT NULL CONSTRAINT DF_SALES_DETAILS_IGSTAMOUNT DEFAULT 0,
        TOTALTAX            NUMERIC(18,2) NOT NULL CONSTRAINT DF_SALES_DETAILS_TOTALTAX DEFAULT 0,
        PERRATE             NUMERIC(18,2) NOT NULL CONSTRAINT DF_SALES_DETAILS_PERRATE DEFAULT 0,
        PRATE               NUMERIC(18,2) NOT NULL CONSTRAINT DF_SALES_DETAILS_PRATE DEFAULT 0,
        TOTALAMOUNT         NUMERIC(18,2) NOT NULL CONSTRAINT DF_SALES_DETAILS_TOTALAMOUNT DEFAULT 0,
        STOCKQTY            NUMERIC(18,2) NOT NULL CONSTRAINT DF_SALES_DETAILS_STOCKQTY DEFAULT 0,
        MFGDATE             DATETIME      NULL,
        EXPDATE             DATETIME      NULL,
        ENTRYID             INT           NOT NULL CONSTRAINT DF_SALES_DETAILS_ENTRYID DEFAULT 0,
        PERPOINTS           INT           NOT NULL CONSTRAINT DF_SALES_DETAILS_PERPOINTS DEFAULT 0,
        SALESPOINTS         INT           NOT NULL CONSTRAINT DF_SALES_DETAILS_SALESPOINTS DEFAULT 0,
        SALESRETURNQTY      INT           NOT NULL CONSTRAINT DF_SALES_DETAILS_SALESRETURNQTY DEFAULT 0,
        FREEITEM            BIT           NOT NULL CONSTRAINT DF_SALES_DETAILS_FREEITEM DEFAULT 0
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'DELIVERY_DETAILS' AND COLUMN_NAME = 'ISSALES')
    ALTER TABLE dbo.DELIVERY_DETAILS ADD ISSALES INT NOT NULL CONSTRAINT DF_DELIVERY_DETAILS_ISSALES DEFAULT 0;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TRIPENTRY' AND COLUMN_NAME = 'ISSALES')
    ALTER TABLE dbo.TRIPENTRY ADD ISSALES INT NOT NULL CONSTRAINT DF_TRIPENTRY_ISSALES DEFAULT 0;
GO
